// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtr4koQPVPB9ug63kEfdyB6kO-GlGqEH4',
    appId: '1:811067035598:web:07cfe2ef2160c4c504a59f',
    messagingSenderId: '811067035598',
    projectId: 'kumpool-be325',
    authDomain: 'kumpool-be325.firebaseapp.com',
    storageBucket: 'kumpool-be325.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuDsL23mX0iWbw8tWzYSw-2NwKROE96f0',
    appId: '1:811067035598:android:e6138befae50ab7204a59f',
    messagingSenderId: '811067035598',
    projectId: 'kumpool-be325',
    storageBucket: 'kumpool-be325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-njfKanM4hk8QGDHikFTNq_pTD1pTJA',
    appId: '1:811067035598:ios:03f7f6115c49b8b104a59f',
    messagingSenderId: '811067035598',
    projectId: 'kumpool-be325',
    storageBucket: 'kumpool-be325.appspot.com',
    iosClientId: '811067035598-433jhgplc7r31avqd410otu9rbu73fnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.kumpool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk-njfKanM4hk8QGDHikFTNq_pTD1pTJA',
    appId: '1:811067035598:ios:03f7f6115c49b8b104a59f',
    messagingSenderId: '811067035598',
    projectId: 'kumpool-be325',
    storageBucket: 'kumpool-be325.appspot.com',
    iosClientId: '811067035598-433jhgplc7r31avqd410otu9rbu73fnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.kumpool',
  );
}
